apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        pp: tomcat
    spec:
      containers:
      - name: tomcat
        image: dockercloud/hello-world
        ports:
        - containerPort: 80